### ISSUE TITLE
Aprender o framework

### ISSUE THREAD

**Issue by ThiagoAquino** [teamworkquality/twq-app#25]
Estudar Vue JS

**Comment by rvlb-19** [comment]
Pessoal, dei uma estudada rápida no Vue.js sobre como trabalhar com forms e fiz um exemplo bem básico disso: https://github.com/rvlb-19/vue-test/blob/master/src/components/Form.vue

Aí já mostra como capturar um evento de submit e também uma forma possível de pegar os valores dos inputs.

obs.: Caso alguém rode o projeto, não estou usando Bootstrap e sim o [bulma.io](bulma.io) (basicamente a mesma coisa, mas sem o JS). Acredito que no nosso caso vai ser mais fácil usar o BS mesmo.

**Comment by ThiagoAquino** [comment]
Massa! Obrigado Renato!
