### ISSUE TITLE
Criar guia para configurar o ambiente de desenvolvimento

### ISSUE THREAD

**Issue by igormatos** [teamworkquality/twq-app#4]
Disponibilizar um README dentro da pasta API, com instruções para que os desenvolvedores consigam configurar seu ambiente.

**Comment by fbormann** [comment]
https://docs.google.com/a/cin.ufpe.br/document/d/17T5G91OVoFDMmXprNOTNFPQ7HRovIaw6V7rvXmgbjso/edit?usp=sharing

**Comment by fbormann** [comment]
Como todos mostraram terem finalizado o guia, vou fechar esta task.
